export const musics = [
  { id: "z0_m1", start: 590, end: 3750 },
  { id: "z1_m1", start: 7600 },
  { id: "z1_m3", start: 8100 },
  { id: "z1_m2" },
  { id: "z3_m1", start: 21800 },
  { id: "z3_m2", start: 18500 },
  { id: "z3_m3", start: 15800 },
  { id: "z3_m4", start: 14100 },
  { id: "z4_m1", start: 22e3 },
  { id: "z5_m1", start: 25e3 },
  { id: "z5_m2", start: 26e3 },
  { id: "z6_m1", start: 28e3 },
  { id: "z7_m1", start: 33800 },
  { id: "z7_m2", start: 33500 },
  { id: "z9_m1", start: 39e3 },
  { id: "z9_m2", start: 39700 },
  { id: "z9_m3", start: 40200 },
  { id: "z10_m1", start: 42800 },
  { id: "z12_m1", start: 57400 },
  { id: "z10_m2", start: 35300, end: 99999 },
  { id: "z10_m3", start: 4500, end: 35e3 }
];

const source = "/";
export const images = [
  { id: "p9_text2", src: source + "img/p9_text2.png" },
  { id: "p0", src: source + "img/p0.png" },
  { id: "p1_face", src: source + "img/p1_face.jpg" },
  { id: "p1_text", src: source + "img/p1_text.png" },
  { id: "p1_eye1", src: source + "img/p1_eye1.png" },
  { id: "p1_eye2", src: source + "img/p1_eye2.png" },
  { id: "p1_sprite", src: source + "img/p1_sprite.png" },
  { id: "p1_tears", src: source + "img/p1_tears.png" },
  { id: "p2_bg1", src: source + "img/p1_bg.png" },
  { id: "p2_bg2", src: source + "img/p1_bg2.png" },
  { id: "p2_m1", src: source + "img/p2_m1.jpg" },
  { id: "p2_m2", src: source + "img/p2_m2.jpg" },
  { id: "p2_m3", src: source + "img/p2_m3.jpg" },
  { id: "p2_m4", src: source + "img/p2_m4.jpg" },
  { id: "p2_monster", src: source + "img/p2_monster.png" },
  { id: "p2_weapon", src: source + "img/p2_weapon.png" },
  { id: "p2_girl2", src: source + "img/p2_girl2.png" },
  { id: "p2_girl3", src: source + "img/p2_girl3.png" },
  { id: "p2_girl2_4", src: source + "img/p2_girl4.png" },
  { id: "p2_fire0", src: source + "img/huo_00088.jpg" },
  { id: "p2_fire1", src: source + "img/huo_00090.jpg" },
  { id: "p2_fire2", src: source + "img/huo_00091.jpg" },
  { id: "p2_fire3", src: source + "img/huo_00092.jpg" },
  { id: "p2_fire4", src: source + "img/huo_00093.jpg" },
  { id: "p2_fire5", src: source + "img/huo_00094.jpg" },
  { id: "p2_fire6", src: source + "img/huo_00095.jpg" },
  { id: "p2_fire7", src: source + "img/huo_00096.jpg" },
  { id: "p2_fire8", src: source + "img/huo_00097.jpg" },
  { id: "p2_fire9", src: source + "img/huo_00098.jpg" },
  { id: "p2_fire10", src: source + "img/huo_00099.jpg" },
  { id: "p2_fire11", src: source + "img/huo_00100.jpg" },
  { id: "p2_fire12", src: source + "img/huo_00101.jpg" },
  { id: "p2_fire13", src: source + "img/huo_00102.jpg" },
  { id: "p2_fire14", src: source + "img/huo_00103.jpg" },
  { id: "p2_fire15", src: source + "img/huo_00104.jpg" },
  { id: "p2_fire16", src: source + "img/huo_00105.jpg" },
  { id: "p2_fire17", src: source + "img/huo_00106.jpg" },
  { id: "p2_fire18", src: source + "img/huo_00107.jpg" },
  { id: "p2_fire19", src: source + "img/huo_00108.jpg" },
  { id: "p2_fire20", src: source + "img/huo_00109.jpg" },
  { id: "p2_fire21", src: source + "img/huo_00110.jpg" },
  { id: "p2_fire22", src: source + "img/huo_00111.jpg" },
  { id: "p2_fire23", src: source + "img/huo_00112.jpg" },
  { id: "p2_fire24", src: source + "img/huo_00113.jpg" },
  { id: "p2_fire25", src: source + "img/huo_00114.jpg" },
  { id: "p2_fire26", src: source + "img/huo_00115.jpg" },
  { id: "p2_fire27", src: source + "img/huo_00116.jpg" },
  { id: "p2_fire28", src: source + "img/huo_00117.jpg" },
  { id: "p2_fire29", src: source + "img/huo_00118.jpg" },
  { id: "p2_fire30", src: source + "img/huo_00119.jpg" },
  { id: "p2_fire31", src: source + "img/huo_00120.jpg" },
  { id: "p2_fire32", src: source + "img/huo_00121.jpg" },
  { id: "p2_fire33", src: source + "img/huo_00122.jpg" },
  { id: "p2_fire34", src: source + "img/huo_00123.jpg" },
  { id: "p2_fire35", src: source + "img/huo_00124.jpg" },
  { id: "p2_fire36", src: source + "img/huo_00125.jpg" },
  { id: "p2_fire37", src: source + "img/huo_00126.jpg" },
  { id: "p2_fire38", src: source + "img/huo_00127.jpg" },
  { id: "p3_clouds", src: source + "img/p3_clouds.png" },
  { id: "p3_bg", src: source + "img/p3_bg.png" },
  { id: "p3_people", src: source + "img/p3_people.png" },
  { id: "p4_bg", src: source + "img/p4_bg.jpg" },
  { id: "p4_craft0", src: source + "img/fengzheng_00000.png" },
  { id: "p4_craft2", src: source + "img/fengzheng_00002.png" },
  { id: "p4_craft4", src: source + "img/fengzheng_00004.png" },
  { id: "p4_craft6", src: source + "img/fengzheng_00006.png" },
  { id: "p4_craft8", src: source + "img/fengzheng_00008.png" },
  { id: "p4_craft10", src: source + "img/fengzheng_00010.png" },
  { id: "p4_craft12", src: source + "img/fengzheng_00012.png" },
  { id: "p4_craft14", src: source + "img/fengzheng_00014.png" },
  { id: "p4_craft16", src: source + "img/fengzheng_00016.png" },
  { id: "p4_craft18", src: source + "img/fengzheng_00018.png" },
  { id: "p4_craft20", src: source + "img/fengzheng_00020.png" },
  { id: "p4_craft22", src: source + "img/fengzheng_00022.png" },
  { id: "p4_craft24", src: source + "img/fengzheng_00024.png" },
  { id: "p4_people1", src: source + "img/p4_people1.png" },
  { id: "p4_people2", src: source + "img/p4_people2.png" },
  { id: "p4_mon1", src: source + "img/p4_mon1.jpg" },
  { id: "p4_mon2", src: source + "img/p4_mon2.jpg" },
  { id: "p4_mon3", src: source + "img/p4_mon3.jpg" },
  { id: "p4_mon4", src: source + "img/p4_mon4.jpg" },
  { id: "p4_mon5", src: source + "img/p4_mon5.jpg" },
  { id: "p4_mon6", src: source + "img/p4_mon6.jpg" },
  { id: "p4_mon7", src: source + "img/p4_mon7.png" },
  { id: "p4_bg2", src: source + "img/p4_bg2.png" },
  { id: "p4_paper", src: source + "img/p4_paper.png" },
  { id: "p4_mon8", src: source + "img/p4_mon8.png" },
  { id: "p5_bg", src: source + "img/p5_bg.png" },
  { id: "p5_mon1", src: source + "img/p5_mon1.png" },
  { id: "p5_mon2", src: source + "img/p5_mon2.png" },
  { id: "p5_mon3", src: source + "img/p5_mon3.png" },
  { id: "p5_mon4", src: source + "img/p5_mon4.png" },
  { id: "p5_window", src: source + "img/p5_window.png" },
  { id: "p5_m0", src: source + "img/p5_m0.png" },
  { id: "p5_m1", src: source + "img/p5_m1.png" },
  { id: "p5_m2", src: source + "img/p5_m2.png" },
  { id: "p5_m3", src: source + "img/p5_m3.png" },
  { id: "p5_text", src: source + "img/p5_text.png" },
  { id: "p6_f0", src: source + "img/p6_f0.png" },
  { id: "p6_f1", src: source + "img/p6_f1.png" },
  { id: "p6_fork", src: source + "img/p6_fork.png" },
  { id: "p6_m", src: source + "img/p6_m.png" },
  { id: "p7_bg", src: source + "img/p7_bg.png" },
  { id: "p7_line", src: source + "img/p7_line.png" },
  { id: "p7_mon1", src: source + "img/p7_mon1.png" },
  { id: "p7_person", src: source + "img/p7_person.png" },
  { id: "p7_person1", src: source + "img/p7_person1.png" },
  { id: "p8_bg1", src: source + "img/p8_bg1.png" },
  { id: "p8_bg2", src: source + "img/p8_bg2.png" },
  { id: "p8_bg3", src: source + "img/p8_bg3.png" },
  { id: "p8_text1", src: source + "img/p8_text1.png" },
  { id: "p8_text2", src: source + "img/p8_text2.png?3" },
  { id: "p8_text3", src: source + "img/p8_text3.png" },
  { id: "p8_text4", src: source + "img/p8_text4.png" },
  { id: "p8_cloud", src: source + "img/p8_cloud.png" },
  { id: "p8_ship", src: source + "img/p8_ship.png" },
  { id: "p8_blood", src: source + "img/p8_blood.png" },
  { id: "p8_blood2", src: source + "img/p8_blood2.png" },
  { id: "p8_fish", src: source + "img/p8_fish.png" },
  { id: "p8_gs1", src: source + "img/gs1.png" },
  { id: "p8_gs2", src: source + "img/gs2.png" },
  { id: "p8_gs3", src: source + "img/gs3.png" },
  { id: "p8_gs4", src: source + "img/gs4.png" },
  { id: "p8_gs5", src: source + "img/gs5.png" },
  { id: "p8_gs6", src: source + "img/gs6.png" },
  { id: "p8_gs7", src: source + "img/gs7.png" },
  { id: "p8_gs8", src: source + "img/gs8.png" },
  { id: "p8_gs9", src: source + "img/gs9.png" },
  { id: "p8_gs10", src: source + "img/gs10.png" },
  { id: "p8_gs11", src: source + "img/gs11.png" },
  { id: "p8_gs12", src: source + "img/gs12.png" },
  { id: "p8_gs13", src: source + "img/gs13.png" },
  { id: "p8_gs14", src: source + "img/gs14.png" },
  { id: "p8_whale1", src: source + "img/p8_whale1.png" },
  { id: "p8_whale2", src: source + "img/p8_whale2.png" },
  { id: "p8_whale3", src: source + "img/p8_whale3.png" },
  { id: "p8_whale5_bg", src: source + "img/p8_whale5_bg.png" },
  { id: "p8_whale5_cover", src: source + "img/p8_whale5_cover.png" },
  { id: "p8_whale5_r", src: source + "img/p8_whale5_r.png" },
  { id: "p8_m1", src: source + "img/p8_m1.png" },
  { id: "p8_m2", src: source + "img/p8_m2.png" },
  { id: "p8_fish2", src: source + "img/p8_fish2.png" },
  { id: "p9_text", src: source + "img/p9_text.png" },
  { id: "p9_text3", src: source + "img/p9_text3.png" },
  { id: "p9_m1", src: source + "img/p9_m1.jpg" },
  { id: "p9_m2", src: source + "img/p9_m2.jpg" },
  { id: "p9_m3", src: source + "img/p9_m3.jpg" },
  { id: "p9_m4", src: source + "img/p9_m4.jpg" },
  { id: "p9_eval", src: source + "img/p9_eval.png" },
  { id: "p9_whale_bg", src: source + "img/p9_whale_bg.png" },
  { id: "p9_lz00", src: source + "img/lz00.png" },
  { id: "p9_lz01", src: source + "img/lz01.png" },
  { id: "p9_lz02", src: source + "img/lz02.png" },
  { id: "p9_lz03", src: source + "img/lz03.png" },
  { id: "p9_lz04", src: source + "img/lz04.png" },
  { id: "p9_lz05", src: source + "img/lz05.png" },
  { id: "p9_lz06", src: source + "img/lz06.png" },
  { id: "p9_lz07", src: source + "img/lz07.png" },
  { id: "p9_lz08", src: source + "img/lz08.png" },
  { id: "p9_lz09", src: source + "img/lz09.png" },
  { id: "p9_lz10", src: source + "img/lz10.png" },
  { id: "p9_lz11", src: source + "img/lz11.png" },
  { id: "p9_lz12", src: source + "img/lz12.png" },
  { id: "p9_lz13", src: source + "img/lz13.png" },
  { id: "p9_lz14", src: source + "img/lz14.png" },
  { id: "p9_lz15", src: source + "img/lz15.png" },
  { id: "p9_lz16", src: source + "img/lz16.png" },
  { id: "p9_lz17", src: source + "img/lz17.png" },
  { id: "p9_lz18", src: source + "img/lz18.png" },
  { id: "p9_lz19", src: source + "img/lz19.png" },
  { id: "p9_lz20", src: source + "img/lz20.png" },
  { id: "p9_lz21", src: source + "img/lz21.png" },
  { id: "p9_lz22", src: source + "img/lz22.png" },
  { id: "p9_lz23", src: source + "img/lz23.png" },
  { id: "p9_lz24", src: source + "img/lz24.png" },
  { id: "p9_lz24", src: source + "img/lz24.png" }
];
